spring:
  profiles:
    active: local
  cloud:
    stream:
      bindings:
        input-insurance-mdm:
          destination: insurance-mdm
          content-type: application/json
          group: insurance-mdm-group
          durableSubscription: true
      default-binder: rabbit